intranet/org/urls.py
from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView

from intranet.org.feeds import LatestDiarys, LatestEvents
from intranet.org.views import (DetailDiary, UpdateShopping,
                                ArchiveIndexEvent, CreateShopping,
                                ArchiveIndexDiary, CreateLend, UpdateLend,
                                MonthArchiveEvent, YearArchiveEvent,
                                MonthArchiveDiary, YearArchiveDiary)
from pipa.ldap.forms import LoginForm


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'intranet.org.views.index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ldappass/', 'pipa.ldap.views.password_change', name='ldap_password_change'),

    url(r'^events/$', login_required(ArchiveIndexEvent.as_view()), name="event_list"),
    url(r'^events/arhiv/(?P<year>\d{4})/$', login_required(YearArchiveEvent.as_view()), name="event_arhive_year"),
    url(r'^events/arhiv/(?P<year>\d{4})/(?P<month>[a-z]{3}|[0-9]{1,2})/$', login_required(MonthArchiveEvent.as_view()), name="event_arhive_month"),
    url(r'^events/create/', 'intranet.org.views.event_edit', name="event_create"),
    url(r'^events/(?P<event_pk>\d+)/edit/$', 'intranet.org.views.event_edit', name="event_edit"),
    url(r'^events/(?P<event_pk>\d+)/diary/edit/$', 'intranet.org.views.event_diary_edit', name="event_diary_edit"),
    url(r'^events/(?P<event_id>\d+)/count/$', 'intranet.org.views.event_count'),
    url(r'^events/(?P<event_id>\d+)/emails/$', 'intranet.org.views.add_event_emails'),
    url(r'^events/(?P<pk>\d+)/technician/take/$', 'intranet.org.views.event_technician_take', name="event_technician_take"),
    url(r'^events/(?P<pk>\d+)/technician/cancel/$', 'intranet.org.views.event_technician_cancel', name="event_technician_cancel"),
    url(r'^events/(?P<pk>\d+)/officer/take/$', 'intranet.org.views.event_officer_take', name="event_officer_take"),
    url(r'^events/(?P<pk>\d+)/officer/cancel/$', 'intranet.org.views.event_officer_cancel', name="event_officer_cancel"),
    url(r'^events/pr/(?P<year>\d{4})/(?P<week>\d{1,2})/$', 'intranet.org.views.event_template'),
    url(r'^events/pr/$', 'intranet.org.views.event_template'),

    url(r'^diarys/$', login_required(ArchiveIndexDiary.as_view()), name="diary_list"),
    url(r'^diarys/add/$', 'intranet.org.views.diarys_form', name="diary_add"),
    url(r'^diarys/(?P<pk>\d+)/$', login_required(DetailDiary.as_view())),
    url(r'^diarys/(?P<id>\d+)/edit/$', 'intranet.org.views.diarys_form', name="diary_edit"),
    (r'^diarys/commit_hook/$', 'intranet.org.views.commit_hook'),
    (r'^diarys/arhiv/(?P<year>\d{4})/$', login_required(YearArchiveDiary.as_view())),
    (r'^diarys/arhiv/(?P<year>\d{4})/(?P<month>[a-z]{3}|[0-9]{1,2})/$', login_required(MonthArchiveDiary.as_view())),

    url(r'^shopping/$', login_required(CreateShopping.as_view()), name="shopping_index"),
    url(r'^shopping/(?P<pk>\d+)/$', login_required(UpdateShopping.as_view()), name="shopping_detail"),
    url(r'^shopping/(?P<id>\d+)/buy/$', 'intranet.org.views.shopping_buy', name="shopping_buy"),
    url(r'^shopping/(?P<id>\d+)/support/$', 'intranet.org.views.shopping_support', name="shopping_support"),
    url(r'^shopping/(?P<id>\d+)/responsible/$', 'intranet.org.views.shopping_responsible', name="shopping_responsible"),

    url(r'^lend/$', login_required(CreateLend.as_view()), name="lend_index"),
    url(r'^lend/(?P<pk>\d+)/$', login_required(UpdateLend.as_view()), name="lend_detail"),
    url(r'^lend/(?P<id>\d+)/back/$', 'intranet.org.views.lend_back', name="lend_back"),

    (r'^tmp_upload/', 'intranet.org.views.temporary_upload'),
    (r'^image_crop_tool/resize/', 'intranet.org.views.image_resize'),
    (r'^image_crop_tool/save/', 'intranet.org.views.image_save'),
    (r'^image_crop_tool/$', 'intranet.org.views.image_crop_tool'),

    (r'^dezurni/$', 'intranet.org.views.dezurni'),
    (r'^dezurni/add/$', 'intranet.org.views.dezurni_add'),
    (r'^dezurni/(?P<year>\d+)/(?P<month>[a-z]{3})/$', 'intranet.org.views.dezurni_monthly'),
    (r'^dezurni/(?P<year>\d+)/(?P<week>\d+)/$', 'intranet.org.views.dezurni'),

    url(r'^member/add$', 'intranet.org.views.add_member', name="add_member"),

    (r'^scratchpad/change/$', 'intranet.org.views.scratchpad_change'),
    url(r'^statistika/(?P<year>\d{4})?', 'intranet.org.views.year_statistics', name='statistics_by_year'),

    # rss
    (r'^feeds/diarys/', LatestDiarys()),
    (r'^feeds/events/', LatestEvents()),

    (r'^addressbook/$', 'pipa.addressbook.views.addressbook'),
    (r'^mercenaries/', include('pipa.mercenaries.urls')),
    url(r'^accounts/login/$', 'pipa.ldap.views.login', {'authentication_form': LoginForm}, name="account_login"),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', name="account_logout"),
    (r'^wiki/$', RedirectView.as_view(url='https://wiki.kiberpipa.org/')),
)

intranet/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import ListView, TemplateView
from feedjack.models import Post


urlpatterns = patterns('',
    (r'^intranet/', include('intranet.org.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog'),
    (r'^grappelli/', include('grappelli.urls')),
    (r'^tinymce/', include('tinymce.urls')),
    (r'^services/ltsp/', include('pipa.ltsp.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^comments/post/$', 'django.contrib.comments.views.comments.post_comment'),
    url(r'^ajax/index/events/$', 'intranet.www.views.ajax_index_events', name="ajax_events"),
    url(r'^ajax/index/events/(?P<year>\d{4})/(?P<week>\d+)/$', 'intranet.www.views.ajax_index_events', name="ajax_events_week"),
    url(r'^ajax/add_mail/(?P<event>[0-9]+)/(?P<email>[^/]*)$', 'intranet.www.views.ajax_add_mail'),
    url(r'^ajax/subscribe_mailinglist/', 'intranet.www.views.ajax_subscribe_mailinglist', name="ajax_subscribe_mailinglist"),
    url(r'^rss/$', TemplateView.as_view(template_name='www/rss.html'), name="rss"),
)

urlpatterns += i18n_patterns('',
    (r'^', include('intranet.www.urls')),
    (r'^gallery/', include('pipa.gallery.urls')),
    (r'^planet/', ListView.as_view(queryset=Post.objects.order_by('-date_modified')[:30])),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intranet/org/models.py
# *-* coding: utf-8 *-*

import time
import re
import urllib
import datetime
from datetime import date, timedelta

from django.db import models
from django.db.models.query import QuerySet
from django.template.defaultfilters import slugify, truncatewords
from django.contrib.auth.models import User
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from tinymce.models import HTMLField

from pipa.mercenaries.models import CostCenter, SalaryType
from intranet.www.templatetags.www import sanitize_html


def to_utc(dt):
    return time.gmtime(time.mktime(dt.timetuple()))

#####
# Managers http://hunterford.me/django-custom-model-manager-chaining/
#####


class EventMixin(object):
    def get_week_events(self, year, week_num):
        """Return events in given week"""
        d = datetime.datetime(year, 1, 1)
        start_d = d + timedelta(days=-d.weekday(), weeks=week_num)
        end_d = d + timedelta(days=-d.weekday(), weeks=week_num + 1)
        return self.get_date_events(start_d, end_d)

    def get_date_events(self, start_d, end_d):
        """Return events in given range"""
        return self.filter(start_date__range=(start_d, end_d)).order_by('start_date')

    def needs_video(self):
        """Return events that still need video"""
        return self.filter(require_video__exact=True).filter(video__isnull=True)

    def has_video(self):
        """Return events that have video recording"""
        return self.filter(video__isnull=False)

    def has_pictures(self):
        """Return events that have pictures information"""
        return self.filter(flickr_set_id__isnull=False)

    def num_total_visitors(self):
        """Return integer of number of total visitors for events"""
        return self.aggregate(models.Sum('visitors'))['visitors__sum']

    def is_public(self):
        """Return public events"""
        return self.filter(public=True)

    def load_related_fields(self):
        """Return related fields that are needed when displaying relevant information"""
        return self.select_related().prefetch_related('officers_on_duty', 'video', 'technician', "diaries", "sodelovanje_set")

    # TODO: average of visitors per event
    #by_project_events = q.values('project__name').annotate(num_visitors=models.Sum('visitors'), num_events=models.Count('project__name')).extra(tables=['org_project'])


class EventQuerySet(QuerySet, EventMixin):
    pass


class EventManager(models.Manager, EventMixin):
    use_for_related_fields = True

    def get_queryset(self):
        return EventQuerySet(self.model, using=self._db)

    def get_author_ids(self):
        return self.values_list('author', flat=True)


#####
# Models
#####


class Tag(models.Model):
    name = models.CharField(max_length=200, primary_key='True')
    total_ref = models.IntegerField(blank=True, default=0)
    font_size = models.IntegerField(blank=True, default=0)
    parent = models.ForeignKey('self', blank=True, null=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/blog/tag/%s/" % (self.name)

    def __cmp__(self, other):
        return cmp(self.total_ref, other.total_ref)


class Project(models.Model):
    name = models.CharField(max_length=100)
    verbose_name = models.CharField(max_length=255, blank=True, null=True)
    responsible = models.ForeignKey(User, blank=True, null=True)
    note = models.TextField(blank=True, null=True)
    email = models.EmailField(blank=True, null=True)

    salary_type = models.ForeignKey(SalaryType, blank=True, null=True)
    salary_rate = models.FloatField(blank=True, null=True)
    cost_center = models.ForeignKey(CostCenter, blank=True, null=True)

    pub_date = models.DateTimeField(auto_now_add=True)
    chg_date = models.DateTimeField(auto_now=True)

    #if True email all people which have this project set, if false email only Project.email
    # this needs null=True or else audit fails miserably
    email_members = models.NullBooleanField(default=True)

    #tags = models.ManyToManyField(Tag, blank=True, null=True)
    parent = models.ForeignKey('self', blank=True, null=True)

    class Meta:
        verbose_name = 'Projekt'
        verbose_name_plural = 'Projekti'
        ordering = ('name',)

    def __unicode__(self):
        return self.name

    def children(self):
        related = []
        children = Project.objects.filter(parent=self)
        for child in children:
            second_level = Project.objects.filter(parent=child)

            if second_level:
                for s in child.children():
                    related.append(s)
            else:
                related.append(child)
        return related


class Category(models.Model):
    name = models.CharField(max_length=100)
    note = models.TextField(blank=True, null=True)

    #tags = models.ManyToManyField(Tag, blank=True, null=True)

    pub_date = models.DateTimeField(auto_now_add=True)
    chg_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'm3c kategorija'
        verbose_name_plural = 'm3c kategorije'

    class Admin:
        js = ('js/tags.js',)


class Place(models.Model):
    name = models.CharField(max_length=100)
    note = models.TextField(blank=True, null=True)
    is_public = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

    class Admin:
        js = ('js/tags.js',)


# subscriber emails, should be onetomany or smth
class Email(models.Model):
    email = models.EmailField(unique=True)

    def __unicode__(self):
        return self.email


class Phone(models.Model):
    phone = models.CharField(max_length=100)

    def __unicode__(self):
        return self.phone


class Organization(models.Model):
    organization = models.CharField(max_length=100)

    def __unicode__(self):
        return self.organization


class IntranetImage(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='events/%Y/%m/', verbose_name="Slikca za Event page")

    class Meta:
        ordering = ('-image',)

    def __unicode__(self):
        return u'Image: %s' % (self.image.url)


# koledar dogodkov
class Event(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField("event_slug", max_length=150, unique=False, blank=True, null=True)

    require_video = models.BooleanField(verbose_name="Bo sneman", default=False)
    # TODO: migrate to is_public
    public = models.BooleanField(verbose_name="Je javen", default=True)

    visitors = models.IntegerField(default=0, verbose_name=u"Številko obiskovalcev", blank=True, null=True)
    language = models.CharField(verbose_name="Jezik", max_length=2, default='sl', choices=settings.LANGUAGES, blank=True, null=True)
    #for iCal
    sequence = models.PositiveIntegerField(default=0)

    slides = models.FileField(upload_to='slides/%Y/%m/', verbose_name="Prosojnice", blank=True, null=True)

    announce = HTMLField(verbose_name="Uradna najava", blank=True, null=True)
    note = HTMLField(verbose_name="Opombe", blank=True, null=True)

    # time fields
    start_date = models.DateTimeField(verbose_name=u"Pričetek", db_index=True)
    end_date = models.DateTimeField(verbose_name=u"Zaključek")
    pub_date = models.DateTimeField(auto_now_add=True)
    chg_date = models.DateTimeField(auto_now=True)

    # relations
    responsible = models.ForeignKey(User, verbose_name="Odgovorna oseba")
    place = models.ForeignKey(Place, verbose_name="Prostor")
    category = models.ForeignKey(Category, verbose_name="Kategorija")
    project = models.ForeignKey(Project, verbose_name="V okviru projekta")
    tags = models.ManyToManyField(Tag, blank=True, null=True)

    require_technician = models.BooleanField(verbose_name="Potrebuje tehnika", default=False)
    technician = models.ManyToManyField(User, verbose_name="Tehnik", blank=True, null=True, related_name="event_technican")

    require_officers_on_duty = models.BooleanField(verbose_name=_(u'Needs officers on duty'), default=True)
    officers_on_duty = models.ManyToManyField(User, verbose_name="Tehnik", blank=True, null=True, related_name="event_officers_on_duty")

    # flickr set id
    # TODO: refactor in new app
    require_photo = models.BooleanField(verbose_name="Bo poslikan", default=True)
    flickr_set_id = models.BigIntegerField(verbose_name="Flickr set ID", blank=True, null=True)

    # for video spamming
    emails = models.ManyToManyField(Email, blank=True, null=True)
    event_image = models.ForeignKey(IntranetImage, verbose_name="Slika", null=True, blank=True)

    # event manager
    objects = EventManager()

    class Meta:
        verbose_name = 'Dogodek'
        verbose_name_plural = 'Dogodki'
        ordering = ('title',)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('event_detail', kwargs=dict(id=self.id, slug=self.slug))

    @property
    def length(self):
        return int(round((self.end_date - self.start_date).seconds / 3600.0))

    def save(self):
        self.slug = slugify(self.title)
        try:
            if Event.objects.get(pk=self.id).__dict__ != self.__dict__:
                self.sequence += 1
        except Event.DoesNotExist:
            pass
        super(Event, self).save()

    def index_image(self):
        index = re.sub('(?P<filename>.*)(?P<ext>\..*)', '\g<filename>-index\g<ext>', self.image._name)
        from os.path import exists
        if exists(settings.MEDIA_ROOT + index):
            return index
        else:
            return self.image._name

    # TODO: migrat to pipa.gallery
    def flickr_url(self):
        return 'http://www.flickr.com/photos/kiberpipa/sets/%s/' % self.flickr_set_id

    def google_calendar_url(self):
        data = [('action', 'TEMPLATE'),

intranet/templates/org/base_bootstrap_fluid_span9.html
{% extends "org/base_bootstrap_fluid.html" %}
{% block main-span-size %}span9{% endblock %}

intranet/templates/org/dezuranje_index.html
{% extends "org/base_bootstrap_fluid.html" %}
{% load box %}

{% block title %}Dnevnik Dežuranja{% endblock %}

{% block title-main %}
	<h1>Dnevnik dežuranja</h1>
	
	Sezona 2011/12, teden #{{ week_number }}
{% endblock %}

{% block navigation %}
		<div class="well">
			<ul class="nav nav-list breadcrumbs">
				<li class="nav-header">Pogledi</li>
				<li class="active"><a href="/intranet/dezurni/{{ year }}/{{ iso_week }}">Tedenski</a></li>
				<li><a href="/intranet/dezurni/{{ year }}/{{ month_name }}">Mesecni</a></li>


				<li class="nav-header">Plache za ta teden</li>
				<li>
					{% box_plache log_list user %}
				</li>
			</ul>
		</div>
		
		<div class="well">
			
			{% box_list Event "start_date__gte=start_date,start_date__lte=end_date" "template=org/list_event.html,order_by=-start_date" %}
		</div>
{% endblock %}

{% block content-main %}
	<div class="module">

		<p></p>

	<table class="dezurni table table-striped table-bordered">
		<tr>
			<th scope="col"><a href="/intranet/dezurni/{{ navigation.prev }}">&lt;&lt;</a> {{ week_number }} <a href="/intranet/dezurni/{{ navigation.next }}">&gt;&gt;</a></th>
			{% ifequal nov_urnik 1 %}
				<th scope="col">1100 - 1600</th>
				<th scope="col">1600 - 2100 </th>
			{% endifequal %}
			{% ifequal nov_urnik 2 %}
				<th scope="col">1000 - 1400</th>
				<th scope="col">1400 - 1800</th>
				<th scope="col">1800 - 2200 </th>
			{% endifequal %}
			{% ifnotequal nov_urnik 2 %}
				{% ifnotequal nov_urnik 1 %}
				<th scope="col">1000 - 1300 </th>
				<th scope="col">1300 - 1600 </th>
				<th scope="col">1600 - 1900</th>
				<th scope="col">1900 - 2200 </th>
				{% endifnotequal %}
			{% endifnotequal %}
		</tr>

		{% for day in week %}
		<tr>
			<td id='date'>{{ day.date }}</td>
			{% for dezurni in day.dezurni %}
				{% if dezurni.name %}
			<td id='dezurni{{ forloop.counter }}'>
			    <a href="#diary_{{ dezurni.admin_id }}" onclick="return diary('#diary_{{ dezurni.admin_id }}');">{{ dezurni.name }}</a>
				<!-- a href="/intranet/diarys/{{ dezurni.admin_id }}/">{{ dezurni.name }}</a-->
				<!--               	<a href="/intranet/dezuranje/view/{{ dezurni.admin_id }}">{{ dezurni.name }}</a> -->
			</td>
				{% else %}
			<td id='dezurni{{ forloop.counter }}' class="free">
				<a class="btn btn-mini" href="javascript:void(0);" onclick="return dezurni('{{ dezurni.unique }}');">Vpiši</a>
			</td>
				{% endif %}
			{% endfor %}
		</tr>
		{% endfor %}
	</table>
	</div>

	{% if not log_list %}
	<div class="module">
		(za ta teden še ni nobenih vpisanih dnevnikov)
	</div>
	{% else %}
		{% for object in log_list %}
			{% print_diary object %}
		{% endfor %}
	{% endif %}

    {% include "org/content/diary_form.html" %}
{% endblock %}

{% block extrahead%}
<script type="text/javascript">
    function diary(diary_id) {
        window.location.hash = diary_id;
        $(".diary").css("background", "white");
        $(diary_id).fadeTo('slow', 0.1, function() { $(this).css("background", "inherit").fadeTo('slow', 1); });
        
        return false;
    }

	function dezurni(id) {
        $('#dnevnikForm').find('input[name=uniqueSpot]').val(id);
        $('#dnevnikForm').modal();
	}

	$(document).ready(function () {
		$('#dnevnikForm input[type=reset]').click(function (e) {
			e.preventDefault();
			$('#dnevnikForm').hide();
		});
	});
</script>
{% endblock %}

intranet/templates/org/dezuranje_text_log.html
Dnevniki

{% for log in log_list %}

## {{ log.date|date:"d.m.Y" }} - {{ log.get_author }}
----------
[Formalni vnos]: {{ log.log_formal }}

[Neformalni vnos]: {{ log.log_informal }}


{% endfor %}

intranet/templates/org/list_task_diary.html
<ul>
{% for obj in object_list %}
    <li onclick="toggle('T{{ obj.id }}')">{{ obj.title }}</li>
{% endfor %}
</ul>

intranet/templates/org/print_event.html
{% load i18n %}
{% load box %}
{% load url from future %}
<tr>
	<td>
		{% if event.start_date|date:"D, d.m.Y" == event.end_date|date:"D, d.m.Y" %}
			{{ event.start_date|date:"d.m.Y"}}&nbsp;{{ event.start_date|date:"(D)" }}<br/>
			{{ event.start_date|date:" H:i" }}-{{ event.end_date|date:"H:i" }}
		{% else %}
			{{ event.start_date|date:"d.m.Y (D) H:i" }}<br/>
			{{ event.end_date|date:"d.m.Y (D) H:i " }}
		{% endif %}
	</td>
	<td>
    	{% if event.note %}
        <i class="icon-warning-sign" title="{{ event.note|html2text }}"></i>
        {% endif %}
		<a href="{% url 'event_edit' event.id %}">{{ event.title }}</a>

		<br/>
		
		{% for sodelovanje in event.sodelovanje_set.all %}
		  <span class="badge">{{ sodelovanje.person }} - {{ sodelovanje.tip }}</span>
		  <br />
		{% endfor %}

		{% if not event.public %}
		  <span class="badge badge-info">Interni</span><br />
		{% endif %}
		{% if event.visitors %}
		  <span class="badge badge-info">{{ event.visitors }} Udeležencev</span><br />
		{% endif %}
		{% if event.emails.count %}
		  <span class="badge {% if event.video.all %}badge-info{% else %}badge-warning{% endif %}">Obveščenih, ko bo video posnetek na voljo: {{ event.emails.count }}</span><br />
		{% endif %}
		
		<span class="badge badge-inverse">{{ event.place.name }}</span>
	</td>
	<td>{{ event.project }}</td>
	<td>
		{% if not event.require_photo and not event.require_video %}
			<i class="icon-blank" title="{% trans 'Video not needed' %}"></i>
			<i class="icon-blank" title="{% trans 'Photos not needed' %}"></i>
		{% endif %}

		{% if event.require_video %}
			{% if event.video.all %}
				{% for video in event.video.all %}
					<a title="{{ video.title }}" href="{{ video.get_absolute_url }}"><i class="icon-film"></i></a>
				{% endfor %}
			{% else %}
				<i class="icon-disabled icon-film" title="{% trans 'Awaiting upload' %}"></i>
			{% endif %}
		{% else %}
			<i class="icon-blank" title="{% trans 'Video not needed' %}"></i>
		{% endif %}

		{% if event.require_photo %}
			{% if event.flickr_set_id %}
				<a href="{{ event.flickr_url }}"><i class="icon-picture"></i></a>
			{% else %}
				<a href="{% url 'event_edit' event.id %}#id_flickr_set_id" class="btn btn-mini btn-warning"><i class="icon-picture icon-disabled"></i> Vnesi</a>
			{% endif %}
		{% else %}
			<i class="icon-blank" title="{% trans 'Photos not needed' %}"></i>
		{% endif %}
	</td>
	<td>
  	<!-- handle technicians -->
		{% for technician in event.technician.all %}
		  <p>
			{% if user == technician %}
				{% if user.id in event.diaries.get_author_ids %}
				<a href="{% url 'event_diary_edit' event_pk=event.id %}#add_diary" class="badge badge-success" title="{% trans 'Edit diary' %}">
				{% else %}
				<a href="{% url 'diary_list' %}?task=23&event={{ event.id }}&length={{ event.length|stringformat:".2d" }}:00:00&date={{ event.start_date|date:"Y/m/d H:s" }}#add_diary" class="badge badge-warning" title="{% trans 'Add diary' %}">
				{% endif %}
					<i class="icon-facetime-video" title="{% trans 'Technician' %}"></i> {{ technician }}
					&nbsp;
					<i class="icon-edit"></i>
					&nbsp;
				</a>
				<p><a class="btn btn-mini" href="{% url 'event_technician_cancel' event.id %}">{% trans "Sign off" %}</a></p>
			<br />
			{% else %}
				<i class="icon-facetime-video" title="{% trans 'Techie' %}"></i> {{ technician }}
			{% endif %}
		  </p>
		{% endfor %}

  	<!-- handle officers -->
		{% for officer in event.officers_on_duty.all %}
			{% if user == officer %}
				{% if user.id in event.diaries.get_author_ids %}
				<a href="{% url 'event_diary_edit' event_pk=event.id %}#add_diary" class="badge badge-success" title="{% trans 'Edit diary' %}">
				{% else %}
				<a href="{% url 'diary_list' %}?task=22&event={{ event.id }}&length={{ event.length|stringformat:".2d" }}:00:00&date={{ event.start_date|date:"Y/m/d H:s" }}#add_diary" class="badge badge-warning" title="{% trans 'Add diary' %}">
				{% endif %}
					<i class="icon-user" title="{% trans 'Officer on duty' %}"></i> {{ officer }}
					&nbsp;
					<i class="icon-edit"></i>
					&nbsp;
				</a>
				<p><a class="btn btn-mini" href="{% url 'event_officer_cancel' event.id %}">{% trans "Sign off" %}</a></p>
			{% else %}
				<i class="icon-user" title="{% trans 'Officer on duty' %}"></i> {{ officer }}
			{% endif %}
			<br />
		{% endfor %}

		<div><!-- to keep buttons in same level-->
		{% if event.require_technician and user not in event.officers_on_duty.all  and user not in event.technician.all %}
			<a href="{% url 'event_technician_take' event.id %}" class="btn btn-small" title="{% trans 'Volunteer as techie' %}"><i class="icon-facetime-video"></i></a>
		{% endif %}
		{% if event.require_officers_on_duty and user not in event.technician.all and user not in event.officers_on_duty.all %}
			<a href="{% url 'event_officer_take' event.id %}" class="btn btn-small" title="{% trans 'Volunteer as officer' %}"><i class="icon-user"></i></a>
		{% endif %}
		</div>

		{% if not event.require_technician and not event.require_officers_on_duty %}
			<span class="badge badge-success">Ne potrebuje</span>
		{% endif %}
	</td>
</tr>