intranet/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import ListView, TemplateView
from feedjack.models import Post


urlpatterns = patterns('',
    (r'^intranet/', include('intranet.org.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog'),
    (r'^grappelli/', include('grappelli.urls')),
    (r'^tinymce/', include('tinymce.urls')),
    (r'^services/ltsp/', include('pipa.ltsp.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^comments/post/$', 'django.contrib.comments.views.comments.post_comment'),
    url(r'^ajax/index/events/$', 'intranet.www.views.ajax_index_events', name="ajax_events"),
    url(r'^ajax/index/events/(?P<year>\d{4})/(?P<week>\d+)/$', 'intranet.www.views.ajax_index_events', name="ajax_events_week"),
    url(r'^ajax/add_mail/(?P<event>[0-9]+)/(?P<email>[^/]*)$', 'intranet.www.views.ajax_add_mail'),
    url(r'^ajax/subscribe_mailinglist/', 'intranet.www.views.ajax_subscribe_mailinglist', name="ajax_subscribe_mailinglist"),
    url(r'^rss/$', TemplateView.as_view(template_name='www/rss.html'), name="rss"),
)

urlpatterns += i18n_patterns('',
    (r'^', include('intranet.www.urls')),
    (r'^gallery/', include('pipa.gallery.urls')),
    (r'^planet/', ListView.as_view(queryset=Post.objects.order_by('-date_modified')[:30])),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intranet/www/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView, DetailView
from haystack.query import SearchQuerySet

from intranet.org.models import Place, Event
from intranet.www.feeds import (
    AllInOne,
    NewsFeed,
    EventsFeed,
    POTFeed,
    SUFeed,
    PlanetFeed,
    MuzejFeed,
)
from intranet.www.views import NewsList


urlpatterns = patterns('',
    url(r'^$', 'intranet.www.views.index', name="index"),
    url(r'^event/(?P<slug>[-\w]*)-(?P<id>\d+)/$', 'intranet.www.views.event', name="event_detail"),
    url(r'^event/\d{4}-[a-z]{3}-[0-9]{1,2}/(?P<id>\d+)/(?P<slug>[^/]*)',
        RedirectView.as_view(url='/event/%(slug)s-%(id)s/', permanent=True)),
    url(r'^event/search/', 'haystack.views.basic_search', dict(
        template='search/search_event.html',
        searchqueryset=SearchQuerySet().models(Event).filter(is_public=True),
        ), name="event_search"),
    url(r'^livestream/$', 'intranet.www.views.livestream', name="livestream"),
    url(r'^livestream/newslide$', 'intranet.www.views.livestream_newslide', name="livestream_newslide"),
    url(r'^news/$', NewsList.as_view(), name="news"),
    url(r'^news/comments/post/$', 'django.contrib.comments.views.comments.post_comment'),
    url(r'^news/(?P<id>\d+)/(?P<slug>[-\w]+)/$', 'intranet.www.views.news_detail'),
    url(r'^news/(?P<id>\d+)/$', 'intranet.www.views.news_detail'),
    url(r'^news/(?P<slug>[-\w]+)/$', 'intranet.www.views.news_detail'),
    url(r'^calendar/$', 'intranet.www.views.calendar', name="calendar"),
    url(r'^calendar/(?P<year>\d{4})/(?P<month>[0-1]?[0-9])?', 'intranet.www.views.calendar'),
    url(r'^calendar/ical/$', 'intranet.www.views.ical', name="calendar_ical"),
    url(r'^prostori/$', 'intranet.www.views.facilities'),
    url(r'^prostori/(?P<pk>\d+)/opis.ajax$', DetailView.as_view(
        queryset=Place.objects.all(),
        template_name="www/facility_description_ajax.html",
    ), name="facility_description_ajax"),
    url(r'^alumni/', 'pipa.addressbook.views.alumni'),
    # TODO: migrate press to flatpages
    url(r'^press/', 'intranet.www.views.press'),
    url(r'^about/', 'intranet.www.views.about', name='about'),

    # converted flatpages to custom templates with some flatpage includes
    url(r'^support/', 'intranet.www.views.support'),

    # feeds
    (r'^feeds/all/', AllInOne()),
    (r'^feeds/novice/', NewsFeed()),
    (r'^feeds/dogodki/', EventsFeed()),
    (r'^feeds/pot/', POTFeed()),
    (r'^feeds/su/', SUFeed()),
    (r'^feeds/planet/', PlanetFeed()),
    (r'^feeds/muzej/', MuzejFeed()),

    # backwards compatibility
    url(r'^press-en/', RedirectView.as_view(url='/en/press/', permanent=True)),
    url(r'^alumni-en/', RedirectView.as_view(url='/en/alumni/', permanent=True)),
    url(r'^calendar-en/', RedirectView.as_view(url='/en/calendar/', permanent=True)),
)

pipa/video/models.py
from django.db import models

from intranet.org.models import Event


class Video(models.Model):
    event = models.ForeignKey(Event, blank=True, null=True, related_name="video")
    image_url = models.CharField(max_length=240)
    play_url = models.CharField(max_length=240)
    pub_date = models.DateField(db_index=True)
    title = models.CharField(max_length=240, blank=True, null=True)
    remote_id = models.CharField(max_length=100, unique=True, null=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return self.play_url

    def get_secure_image_url(self):
        # TODO: for now redirect to our page until v.k.o support https
        return 'https://www.kiberpipa.org/videothumb/%s.jpg' % self.image_url.replace('/image-i.jpg', '').replace('http://video.kiberpipa.org/media/', '')

intranet/www/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
from django.forms import widgets
from django.conf import settings
from django.utils.translation import ugettext as _

from intranet.org.models import Place
from intranet.www.models import News

from tinymce.widgets import TinyMCE

class EmailForm(forms.Form):
    email = forms.EmailField()


# http://plugins.jquery.com/project/datetime
class EventContactForm(forms.Form):
    # TODO: upgrade jquery and use internal
    class Media:
        js = (
            'http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js',
            'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.8/jquery-ui.min.js',
            settings.STATIC_URL + 'www/js/jquery.ui.datetime.min.js',
        )
        css = {'all': (
            'http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/ui-darkness/jquery-ui.css',
            settings.STATIC_URL + 'www/css/jquery.ui.datetime.css',
        )}

    facility = forms.ModelChoiceField(label=_(u'Space'),
        queryset=Place.objects.filter(is_public=True),
        )
    start_time = forms.DateTimeField(label=_(u'Event start'),
        input_formats=settings.DATETIME_INPUT_FORMATS,
        widget=widgets.DateTimeInput(attrs={'class': 'datetime-ui'}))
    end_time = forms.DateTimeField(label=_(u'Event end'),
        input_formats=settings.DATETIME_INPUT_FORMATS,
        widget=widgets.DateTimeInput(attrs={'class': 'datetime-ui'}))
    text = forms.CharField(label=_(u'Event description'), widget=widgets.Textarea)
    contact = forms.EmailField(label=_(u'Contact person (email)'))


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'image', 'text', 'language', 'author']
        widgets = {
            'text' : TinyMCE(mce_attrs={'height': 300}), # make it higher
        }
            

intranet/www/views.py
# *-* coding: utf-8 *-*

import datetime
import logging
import re
import ssl
import urllib2
import urlparse
import socket
import json as simplejson
from calendar import Calendar

import icalendar
import pytz

from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.core.mail import send_mail
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.template.defaultfilters import striptags, safe, truncatewords
from django.template import RequestContext, Context
from django.template.loader import get_template
from django.utils.translation import ugettext as _
from django.utils.dateformat import format as format_
from django.views.decorators.csrf import csrf_protect
from django.views.generic import ListView
from django_mailman.models import List
from feedjack.models import Post
from haystack.query import SearchQuerySet
from raven.contrib.django.raven_compat.models import client
import twitter

from intranet.org.models import Event, Email
from intranet.www.models import News
from intranet.www.forms import EmailForm, EventContactForm
from pipa.video.models import Video
from pipa.video.utils import is_streaming, get_streaming_event, get_next_streaming_event
from pipa.gallery.templatetags.photos_box import api as flickr_api


logger = logging.getLogger(__name__)
ljubljana_tz = pytz.timezone('Europe/Ljubljana')


def sort_news(x, y):
    date_x = x.date if 'date' in dir(x) else x.date_modified
    date_y = y.date if 'date' in dir(y) else y.date_modified

    return date_x < date_y


# TODO: http://stackoverflow.com/questions/2268417/expire-a-view-cache-in-django
def index(request):
    """
        Load everything we need for the frontpage
        And that's a lot of stuff

    """
    # load news items (internal) and blog posts (members' blogs, fetched via rss)
    news = News.objects.select_related().order_by('-date')[:4]
    posts = Post.objects.order_by('-date_modified')[:4]
    videos = Video.objects.order_by('-pub_date')[:5]

    # splice both of them together into one list, and sort them by date
    # but the most recent news items always comes first, even if older
    # tiny technicality - their respective models use a different date field
    both = []
    both.extend(news[1:])
    for post in posts:
        post.date = post.date_modified
        both.append(post)
    both2 = sorted(both, cmp=sort_news, reverse=True)
    if news:
        both2.insert(0, news[0])

    # load some tweets
    # TODO: https://github.com/bear/python-twitter/issues/21
    tweets = []
    originals = []
    if hasattr(settings, "TWITTER_CONSUMER_KEY"):
        api = twitter.Api(
            consumer_key=settings.TWITTER_CONSUMER_KEY,
            consumer_secret=settings.TWITTER_CONSUMER_SECRET,
            access_token_secret=settings.TWITTER_ACCESS_TOKEN_SECRET,
            access_token_key=settings.TWITTER_ACCESS_TOKEN_KEY,
        )

        try:
            tweets = api.GetSearch(term='kiberpipa OR cyberpipe', count=50, include_entities=True)
            tweets_map = dict((tweet.id, tweet) for tweet in tweets) # for faster lookup by id
            originals = filter(lambda x : not x.retweeted_status, tweets) # original tweets, aka not rts

            # unshorten urls
            for tweet in tweets:
                if tweet.retweeted_status is not None:
                    tweet.text = tweet.retweeted_status.text
                    # unshorten urls for retweets (yes twitter api sux)
                    for url in tweet.retweeted_status.urls:
                        tweet.text = tweet.text.replace(url.url, url.expanded_url)
                for url in tweet.urls:
                    tweet.text = tweet.text.replace(url.url, url.expanded_url)

                # resolve mentions, hashtags
                for mention in tweet.user_mentions:
                    name = mention.screen_name
                    # sometimes, people will write mentions by hand, in the wrong case (eg. "@gittip" when the acc is really @Gitttip).
                    # if we were to use the vanilla (case-sensitive) .replace(), we wouln't have been able to catch these buggers
                    tweet.text = re.sub(re.compile("@" + name, re.I),
                        """<a rel="nofollow" target="_blank" href="https://twitter.com/%s">@%s</a>""" % (mention.screen_name, mention.screen_name),
                        tweet.text) 
                for hashtag in tweet.hashtags:
                    tweet.text = tweet.text.replace("#" + hashtag.text, 
                        """<a rel="nofollow" target="_blank" href="https://twitter.com/search?q=%s&amp;src=hash">#%s</a>""" % (hashtag.text, hashtag.text))

                # merge all retweets under the original tweet
                if tweet.retweeted_status:
                    rt_id = tweet.retweeted_status.id
                    # the odd case that the original tweet was not among the most recent ones
                    if not rt_id in tweets_map:
                        fake_rt = tweet.retweeted_status
                        fake_rt.__setattr__('rts', []);                   
                        tweets_map[rt_id] = fake_rt

                    # add the retweet to the "rts" list on the original tweet
                    rt = tweets_map[rt_id]
                    if not hasattr(rt, "rts"):
                        rt.__setattr__('rts', [])
                    rt.rts.append(tweet)
        except (urllib2.URLError, socket.timeout, twitter.TwitterError, ssl.SSLError):
            client.captureException()

    # recent flickr uploads
    try:
        pictures = []
        # http://www.flickr.com/services/api/flickr.photosets.getList.html
        json = flickr_api.flickr_call(
            method='flickr.photosets.getList',
            user_id='40437802@N07',  # http://idgettr.com/
            per_page=5,
            pages=1,
            format="json",
            nojsoncallback=1)
    except (urllib2.URLError, socket.timeout, ssl.SSLError):
        client.captureException()
    else:
        r = simplejson.loads(json)
        if r.get('stat', 'error') == 'ok':
            photosets = r['photosets']['photoset']
            photosets = sorted(photosets, key=lambda x: x['date_create'], reverse=True)
            for image in photosets[:7]:
                if int(image['photos']) == 0:
                    continue
                image['thumb_url'] = settings.PHOTOS_FLICKR_SET_IMAGE_URL_N % image
                image['url'] = 'http://www.flickr.com/photos/kiberpipa/sets/%(id)s/' % image
                image['title'] = image['title']['_content']
                pictures.append(image)

    return render_to_response('www/index.html', {
        'news': news,
        'planet': posts,
        'both': both2,
        'videos': videos,
        'tweets': tweets,
        'original_tweets' : originals[:20],
        'pictures': pictures,
    }, context_instance=RequestContext(request))


def ajax_index_events(request, year=None, week=None):
    today = datetime.date.today()
    if year is None and week is None:
        # for default view display next public event first
        try:
            e = Event.objects.filter(public=True,
                                     start_date__gte=today).order_by('start_date')[0]
            today = e.start_date.date()
        except IndexError:
            pass
    week = int(week or today.isocalendar()[1])
    year = int(year or today.year)

    # %Y: year,
    # %W: week of the year (starting with first monday of the year),
    # %w: weekday (0 being sunday)
    start = week_start_date(year, week)
    end = start + relativedelta(days=7)

    # get all events in this week
    # TODO: this will fail for events that last more than a week
    # TODO: for this purpose, we should just use postgres daterange sooner or later.
    q = Event.objects.filter(public=True,
                             start_date__range=(start, end),
                             end_date__range=(start, end))
    events = q.order_by('start_date').all()

    # figure out if we are streaming now
    streaming_event = None
    if week == int(today.isocalendar()[1]) and is_streaming():
        streaming_event = get_streaming_event()

    # TODO: a bug with calculating week number
    prev_week_date = start - relativedelta(days=7)
    next_week_date = start + relativedelta(days=7)
    ret = dict()
    ret['prev_url'] = reverse('ajax_events_week', kwargs=dict(year=prev_week_date.isocalendar()[0], week=prev_week_date.isocalendar()[1]))
    ret['next_url'] = reverse('ajax_events_week', kwargs=dict(year=next_week_date.isocalendar()[0], week=next_week_date.isocalendar()[1]))
    ret['events'] = {}

    dict_events = []

    for event in events:
        d = dict(id=event.id,
                 title=event.title,
                 start_date=ljubljana_tz.localize(event.start_date),
                 end_date=ljubljana_tz.localize(event.end_date),
                 place=event.place.name,
                 url=event.get_absolute_url())
        d['project'] = event.project.verbose_name or event.project.name
        d['announce'] = truncatewords(safe(striptags(event.announce)), 50)
        d['image'] = event.event_image.image.url
        if streaming_event:
            d['is_streaming'] = streaming_event.id == event.id
        else:
            d['is_streaming'] = False
        dict_events.append(d)

    # group by events with the days in a week
    for i, day in enumerate(map(lambda i: start + relativedelta(days=i), range(0, 7))):
        ret['events'][i] = dict(
            date=format_(day, 'D, d. b').capitalize(),
            short_date=format_(day, 'd. n.'),
            events=[],
            is_today=day == today,
        )
        for event in dict_events:

templates/www/alumni-en.html
{% extends "www/base-second.html" %}

{% load www %}

{% block content %}
    <div id="community">
    	<div class="community-title">
        Community
        </div>
        <div class="community-text">
Kiberpipa is possible because of all the volunteers that are interested in tech, computers, art and the mix of everything through everyday life. Through the years there were many people that helped around, some stayed for a short while, while others are still helping around. Here is a list of people that helped in anyway and build Kiberpipa to be The Best Cybercenter in Europe.
        </div>
        <div class="community-title2">
        Active
        </div>
            <div class="community-content">
                {% for alumni in active %}
            <div class="community-person">
            <div class="community-content-img"><img src="{% if alumni.image %}{{ alumni.image.url }}{% else %}{{ media_url }}/www/images/picture-skupnost.gif{% endif %}" width="80px" height="80px" /></div>
            <div class="community-details">
            <p class="alumni-title-p">{{ alumni.user.get_full_name }}</p>
            {% if alumni.mail %}
                <p class="alumni-desc">Mail: {{ alumni.mail|spam }}</p>
            {% endif %}
            {% if alumni.www %}
                <p class="alumni-desc">Web: <a href="{{ alumni.www }}">{{ alumni.www }}</a></p>
            {% endif %}
            {% if alumni.blog %}
                <p class="alumni-desc">Blog: <a href="{{ alumni.blog }}">{{ alumni.blog }}</a></p>
            {% endif %}
            {% if alumni.phone %}
                <p class="alumni-desc">{{ alumni.phone }}</p>
            {% endif %}
            </div>
            <div class="alumni-text">
            <p>{{ alumni.text }}</p>
            </div>
            <div class="community-img-s">
            {% if alumni.twitter %}
                <a href="{{ alumni.twitter }}"><img src="{{ media_url }}/www/images/twitter20x20.png" alt="Twitter" title="Twitter" /></a>
            {% endif %}
            {% if alumni.facebook %}
                <a href="{{ alumni.facebook }}"><img src="{{ media_url }}/www/images/facebook20x20.png" alt="Facebook" title="Facebook" /></a>
            {% endif %}
            {% if alumni.linkedin %}
                <a href="{{ alumni.linkedin }}"><img src="{{ media_url }}/www/images/linkedin20x20.png" alt="LinkedIn" title="LikedIn" /></a>
            {% endif %}
            {% if alumni.flickr %} 
                <a href="{{ alumni.flickr }}"><img src="{{ media_url }}/www/images/flickr20x20.png" alt="Flickr" title="Flickr" /></a>
            {% endif %}
            {% if alumni.jabber %}
                <a href="{{ alumni.jabber }}"><img src="{{ media_url }}/www/images/gtalk20x20.png" alt="Google Talk" title="Google Talk" /></a>
            {% endif %}
            {% if alumni.msn %}
                <a href="{{ alumni.msn }}"><img src="{{ media_url }}/www/images/msn20x20.png" alt="MSN Chat" title="MSN Chat" /></a>
            {% endif %}
            {% if alumni.yahoo %}
                <a href="{{ alumni.yahoo }}"><img src="{{ media_url }}/www/images/yahoo20x20.png" alt="Yahoo" title="Yahoo" /></a>
            {% endif %}
            {% if alumni.skype %}
                <a href="{{ alumni.skype }}"><img src="{{ media_url }}/www/images/skype20x20.png" alt="Skype" title="Skype" /></a>
            {% endif %}
            </div>
            </div>
        {% endfor %}
{% if not_active %}
        <div class="community-title2">
        Not active
        </div>
                {% for alumni in not_active %}
            <div class="community-person">
            <div class="community-content-img"><img src="{% if alumni.image %}{{ alumni.image.url }}{% else %}{{ media_url }}/www/images/picture-skupnost.gif{% endif %}" width="80px" height="80px" /></div>
            <div class="community-details">
            <p class="alumni-title-p">{{ alumni.user.get_full_name }}</p>
            {% if alumni.mail %}
                <p class="alumni-desc">Mail: {{ alumni.mail|spam }}</p>
            {% endif %}
            {% if alumni.www %}
                <p class="alumni-desc">Web: <a href="{{ alumni.www }}">{{ alumni.www }}</a></p>
            {% endif %}
            {% if alumni.blog %}
                <p class="alumni-desc">Blog: <a href="{{ alumni.blog }}">{{ alumni.blog }}</a></p>
            {% endif %}
            {% if alumni.phone %}
                <p class="alumni-desc">{{ alumni.phone }}</p>
            {% endif %}
            </div>
            <div class="alumni-text">
            <p>{{ alumni.text }}</p>
            </div>
            <div class="community-img-s">
            {% if alumni.twitter %}
                <a href="{{ alumni.twitter }}"><img src="{{ media_url }}/www/images/twitter20x20.png" alt="Twitter" title="Twitter" /></a>
            {% endif %}
            {% if alumni.facebook %}
                <a href="{{ alumni.facebook }}"><img src="{{ media_url }}/www/images/facebook20x20.png" alt="Facebook" title="Facebook" /></a>
            {% endif %}
            {% if alumni.linkedin %}
                <a href="{{ alumni.linkedin }}"><img src="{{ media_url }}/www/images/linkedin20x20.png" alt="LinkedIn" title="LikedIn" /></a>
            {% endif %}
            {% if alumni.flickr %} 
                <a href="{{ alumni.flickr }}"><img src="{{ media_url }}/www/images/flickr20x20.png" alt="Flickr" title="Flickr" /></a>
            {% endif %}
            {% if alumni.jabber %}
                <a href="{{ alumni.jabber }}"><img src="{{ media_url }}/www/images/gtalk20x20.png" alt="Google Talk" title="Google Talk" /></a>
            {% endif %}
            {% if alumni.msn %}
                <a href="{{ alumni.msn }}"><img src="{{ media_url }}/www/images/msn20x20.png" alt="MSN Chat" title="MSN Chat" /></a>
            {% endif %}
            {% if alumni.yahoo %}
                <a href="{{ alumni.yahoo }}"><img src="{{ media_url }}/www/images/yahoo20x20.png" alt="Yahoo" title="Yahoo" /></a>
            {% endif %}
            {% if alumni.skype %}
                <a href="{{ alumni.skype }}"><img src="{{ media_url }}/www/images/skype20x20.png" alt="Skype" title="Skype" /></a>
            {% endif %}
            </div>
            </div>
        {% endfor %}
{% endif %}
            </div>        
        
{% endblock %}

templates/www/event.html
{% extends "www/base-second.html" %}
{% block extrahead %}{% endblock %}
{% block title %}{{ event }}{% endblock %}
{% load markup %}

{% block heading %}
    <h1>{{ event }}</h1>
{% endblock %}
{% block content%}
    <div id="dogodek">
        <div class="dogodek-news-title">
        {{ event }}
        </div>
        {{ event.start_date|date:"l, d. "|capfirst }}
        {{ event.start_date|date:"b Y"|capfirst }}
        <div class="dogodek-content">
        <div class="dogoodek-content img">
        {% if event.image %}
            <img src="{{ event.image.url }}" alt="slika" />
        {% else %}
            <img src="http://upload.wikimedia.org/wikipedia/commons/4/47/Placeholder.png" />
        {% endif %}
        </div>
        {{ event.announce|safe|linebreaks }}
        </div>
        {% comment %} <div class="dogodek-tags">Znake: Lorem, Ipsum, Dolor, Sit, Amet</div> {% endcomment %}
        {% comment %}
        <div class="dogodek-gallery">
        	<div class="dogodek-gallery-title">
            Pictures from Gallery
            </div>
            {% if event.gallery_set.all %}
                {% for gallery in event.gallery_set.all %}
                    {% for photo in gallery.photos.all %}
                        <div class="dogodek-gallery-button{{ forloop.counter }}">
                            <img src="{{ photo.get_normal_url }}" alt="slika" />
                        </div>
                    {% endfor %}
                {% endfor %}
        	<div class="dogodek-gallery-more">See more in Gallery &gt;&gt;</div>
            {% else %}
                uggh, dezurni should be spanked.
            {% endif %}
        </div>
        {% endcomment %}
        <div class="dogodek-video">
        	<div class="dogodek-video-title">
        	<a href="http://video.kiberpipa.org">Video arhiv</a>
            </div>
            {% for video in event.video_set.all %}
                <div class="dogodek-video-button">
                    <a href="{{ video.play_url }}"><img width="80" height="80" src="{{ video.image_url }}" alt="slika" /></a>
                </div>
            {% endfor %}
        </div>
        {% comment %}
        <div class="dogodek-related">
        	<div class="dogodek-related-title">
            Related articles:
            </div>
        	<ul>
        		<li>Related article 01</li>
            	<li>Related article 02</li>
            	<li>Related article 03</li>
            	<li>Related article 04</li>
            	<li>Related article 05</li>
        	</ul>
        </div>
        {% endcomment %}
    </div>
{% load comments %}

<div class="dogodek-komentarji">
<p class="title-kom">Komentarji:</p>

{% get_comment_list for event as comment_list %}
{% for comment in comment_list %}
	<p class="komentar-avtor"><a href="{{ comment.url }}">{{ comment.name }}</a> je napisal:</p>
	<p class="date-kom">{{ comment.submit_date|date:"j N Y, H:i" }}</p>
	<p class="komentar-vsebina">{{ comment.comment }}</p>
{% endfor %}



{% get_comment_form for event as form %}
<div class="komentar-poslji">
<form action="{% comment_form_target %}" method="POST">
  {{ form.as_ul }}
  <li class="submit">
    <input type="submit" name="submit" class="submit-post" value="Pošlji komentar">
  </li>
</form>
</div>
    </div>
{% endblock %}

templates/www/news.html
{% extends "www/base-second.html" %}
{% block content %}
    <div id="blog-news">
    	<div class="blog-news-title">
        Kiberpipin blog
        </div>
        <div class="blog-news-en-title">
        {{ news }}
        </div>
        <div class="blog-news-publish">
        Published by {{ news.author }} on {{ news.date }}
        </div>
        <div class="blog-news-content">
        <div class="blog-news-content img"> {{ news.image }}</div>
						{{ news.text|safe }}
        </div>

{% load comments %}

<div class="dogodek-komentarji">
<p class="title-kom">Komentarji:</p>

{% get_comment_list for news as comment_list %}
{% for comment in comment_list %}
	<p class="komentar-avtor"><a href="{{ comment.url }}">{{ comment.name }}</a> je napisal:</p>
	<p class="date-kom">{{ comment.submit_date|date:"j N Y, H:i" }}</p>
	<p class="komentar-vsebina">{{ comment.comment }}</p>
{% endfor %}



{% get_comment_form for news as form %}
<form action="{% comment_form_target %}" method="POST">
  {{ form.as_ul }}
  <li class="submit">
    <input type="submit" name="submit" class="submit-post" value="Pošlji komentar">
  </li>
</form>
</div>
{% endblock %}